// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package formula1backend.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ODataFilterYear extends UserAction<java.lang.Long>
{
	private final java.lang.String Uri;
	private final java.lang.String Field;
	private final java.lang.Long Fallback;

	public ODataFilterYear(
		IContext context,
		java.lang.String _uri,
		java.lang.String _field,
		java.lang.Long _fallback
	)
	{
		super(context);
		this.Uri = _uri;
		this.Field = _field;
		this.Fallback = _fallback;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE

		return formula1backend.ODataQuery.filterLong(Uri, Field, Fallback);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ODataFilterYear";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
