// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package formula1backend.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ODataOrderLimitSql extends UserAction<java.lang.String>
{
	private final java.lang.String Uri;
	private final java.lang.String ColumnMap;
	private final java.lang.String DefaultOrderBy;
	private final java.lang.Long MaxTop;

	public ODataOrderLimitSql(
		IContext context,
		java.lang.String _uri,
		java.lang.String _columnMap,
		java.lang.String _defaultOrderBy,
		java.lang.Long _maxTop
	)
	{
		super(context);
		this.Uri = _uri;
		this.ColumnMap = _columnMap;
		this.DefaultOrderBy = _defaultOrderBy;
		this.MaxTop = _maxTop;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		return formula1backend.ODataQuery.orderLimit(Uri, ColumnMap, DefaultOrderBy, MaxTop);

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ODataOrderLimitSql";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
