// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package formula1backend.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class Sync_Sleep extends UserAction<java.lang.Boolean>
{
	private final java.lang.Long Seconds;

	public Sync_Sleep(
		IContext context,
		java.lang.Long _seconds
	)
	{
		super(context);
		this.Seconds = _seconds;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE

		long s = Seconds == null ? 0L : Seconds.longValue();
		    if (s < 0) s = 0;
		    if (s > 60) s = 60;
		    try {
		        Thread.sleep(s * 1000L);
		        return true;
		    } catch (InterruptedException e) {
		        Thread.currentThread().interrupt();
		        return false;
		    }

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Sync_Sleep";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
